
package com.tracfone.b2b.accountservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountServices", targetNamespace = "http://b2b.tracfone.com/AccountServices", wsdlLocation = "http://dp-sit1-soa3:9001/B2B/AccountServices?wsdl")
public class AccountServices_Service
    extends Service
{

    private final static URL ACCOUNTSERVICES_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTSERVICES_EXCEPTION;
    private final static QName ACCOUNTSERVICES_QNAME = new QName("http://b2b.tracfone.com/AccountServices", "AccountServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dp-sit1-soa3:9001/B2B/AccountServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTSERVICES_WSDL_LOCATION = url;
        ACCOUNTSERVICES_EXCEPTION = e;
    }

    public AccountServices_Service() {
        super(__getWsdlLocation(), ACCOUNTSERVICES_QNAME);
    }

    public AccountServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTSERVICES_QNAME, features);
    }

    public AccountServices_Service(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTSERVICES_QNAME);
    }

    public AccountServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTSERVICES_QNAME, features);
    }

    public AccountServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountServices
     */
    @WebEndpoint(name = "AccountServicesSOAP")
    public AccountServices getAccountServicesSOAP() {
        return super.getPort(new QName("http://b2b.tracfone.com/AccountServices", "AccountServicesSOAP"), AccountServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountServices
     */
    @WebEndpoint(name = "AccountServicesSOAP")
    public AccountServices getAccountServicesSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://b2b.tracfone.com/AccountServices", "AccountServicesSOAP"), AccountServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTSERVICES_EXCEPTION!= null) {
            throw ACCOUNTSERVICES_EXCEPTION;
        }
        return ACCOUNTSERVICES_WSDL_LOCATION;
    }

}
