
package com.tracfone.b2b.accountservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountServices", targetNamespace = "http://b2b.tracfone.com/AccountServices")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.tracfone.runtimefault.ObjectFactory.class,
    com.tracfone.organizationcommontypes.ObjectFactory.class,
    com.tracfone.accountcommontypes.ObjectFactory.class,
    com.tracfone.b2b.accountservices.ObjectFactory.class,
    com.tracfone.carriercommontypes.ObjectFactory.class,
    com.tracfone.commontypes.ObjectFactory.class,
    com.tracfone.paymentcommontypes.ObjectFactory.class,
    com.tracfone.phonecommontypes.ObjectFactory.class,
    com.tracfone.securitycommontypes.ObjectFactory.class,
    com.tracfone.serviceplancommontypes.ObjectFactory.class
})
public interface AccountServices {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.SubmitE911AddressCaseResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/submitE911AddressCase")
    @WebResult(name = "submitE911AddressCaseResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public SubmitE911AddressCaseResponseType submitE911AddressCase(
        @WebParam(name = "submitE911AddressCaseRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        SubmitE911AddressCaseRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AddressInformationResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/insertE911AddressInformation")
    @WebResult(name = "insertE911AddressInformationResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AddressInformationResponseType insertE911AddressInformation(
        @WebParam(name = "insertE911AddressInformationRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AddressInformationRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AddressInformationResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/updateE911AddressInformation")
    @WebResult(name = "updateE911AddressInformationResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AddressInformationResponseType updateE911AddressInformation(
        @WebParam(name = "updateE911AddressInformationRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AddressInformationRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.TimeAsCustomerResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/getTimeAsCustomer")
    @WebResult(name = "getTimeAsCustomerResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public TimeAsCustomerResponseType getTimeAsCustomer(
        @WebParam(name = "getTimeAsCustomerRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        TimeAsCustomerRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AccountValidationResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/validateAccount")
    @WebResult(name = "validateAccountResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AccountValidationResponseType validateAccount(
        @WebParam(name = "validateAccountRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AccountValidationRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AccountValidationResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/validateAccountMB")
    @WebResult(name = "validateAccountResponseMB", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AccountValidationResponseType validateAccountMB(
        @WebParam(name = "validateAccountRequestMB", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AccountValidationRequestTypeMB parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AccountCreationResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/createAccount")
    @WebResult(name = "createAccountResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AccountCreationResponseType createAccount(
        @WebParam(name = "createAccountRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AccountCreationRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AccountSecurityQuestionsLookupResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/getAccountSecurityQuestions")
    @WebResult(name = "getAccountSecurityQuestionResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AccountSecurityQuestionsLookupResponseType getAccountSecurityQuestions(
        @WebParam(name = "getAccountSecurityQuestionsRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AccountSecurityQuestionsLookupRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AccountUpdateResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/updateAccount")
    @WebResult(name = "updateAccountResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AccountUpdateResponseType updateAccount(
        @WebParam(name = "updateAccountRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AccountUpdateRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.RemoveEsnFromAccountResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/removeEsnFromAccount")
    @WebResult(name = "removeEsnFromAccountResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public RemoveEsnFromAccountResponseType removeEsnFromAccount(
        @WebParam(name = "removeEsnFromAccountRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        RemoveEsnFromAccountRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.GetEsnListByCriteriaResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/getEsnListByCriteria")
    @WebResult(name = "getEsnListByCriteriaResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public GetEsnListByCriteriaResponseType getEsnListByCriteria(
        @WebParam(name = "getEsnListByCriteriaRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        GetEsnListByCriteriaRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AddEsnToAccountResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/addEsnToAccount")
    @WebResult(name = "addEsnToAccountResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AddEsnToAccountResponseType addEsnToAccount(
        @WebParam(name = "addEsnToAccountRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AddEsnToAccountRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.ResetPasswordResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/resetPassword")
    @WebResult(name = "resetPasswordResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public ResetPasswordResponseType resetPassword(
        @WebParam(name = "resetPasswordRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        ResetPasswordRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.GetAccountSummaryResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/getAccountSummary")
    @WebResult(name = "getAccountSummaryResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public GetAccountSummaryResponseType getAccountSummary(
        @WebParam(name = "getAccountSummaryRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        GetAccountSummaryRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.ForgotPasswordResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/forgotPassword")
    @WebResult(name = "forgotPasswordResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public ForgotPasswordResponseType forgotPassword(
        @WebParam(name = "forgotPasswordRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        ForgotPasswordRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.AccountRecoveryAccountStatusResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/isValidAccount")
    @WebResult(name = "isValidAccountResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public AccountRecoveryAccountStatusResponseType isValidAccount(
        @WebParam(name = "isValidAccountRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        AccountRecoveryAccountStatusRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.accountservices.GetAccountDetailsResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/AccountServices/getAccountDetails")
    @WebResult(name = "getAccountDetailsResponse", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
    public GetAccountDetailsResponseType getAccountDetails(
        @WebParam(name = "getAccountDetailsRequest", targetNamespace = "http://b2b.tracfone.com/AccountServices", partName = "parameters")
        GetAccountDetailsRequestType parameters);

}
