
package com.tracfone.b2b.redemptionservices;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RedemptionServices", targetNamespace = "http://b2b.tracfone.com/RedemptionServices/", wsdlLocation = "http://dp-sit1-soa3:9001/B2B/RedemptionServices?wsdl")
@HandlerChain(file="../../handlers/handlers.xml")
public class RedemptionServices_Service
    extends Service
{

    private final static URL REDEMPTIONSERVICES_WSDL_LOCATION;
    private final static WebServiceException REDEMPTIONSERVICES_EXCEPTION;
    private final static QName REDEMPTIONSERVICES_QNAME = new QName("http://b2b.tracfone.com/RedemptionServices/", "RedemptionServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dp-sit1-soa3:9001/B2B/RedemptionServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REDEMPTIONSERVICES_WSDL_LOCATION = url;
        REDEMPTIONSERVICES_EXCEPTION = e;
    }

    public RedemptionServices_Service() {
        super(__getWsdlLocation(), REDEMPTIONSERVICES_QNAME);
    }

    public RedemptionServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REDEMPTIONSERVICES_QNAME, features);
    }

    public RedemptionServices_Service(URL wsdlLocation) {
        super(wsdlLocation, REDEMPTIONSERVICES_QNAME);
    }

    public RedemptionServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REDEMPTIONSERVICES_QNAME, features);
    }

    public RedemptionServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RedemptionServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RedemptionServices
     */
    @WebEndpoint(name = "RedemptionServicesSOAP")
    public RedemptionServices getRedemptionServicesSOAP() {
        return super.getPort(new QName("http://b2b.tracfone.com/RedemptionServices/", "RedemptionServicesSOAP"), RedemptionServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RedemptionServices
     */
    @WebEndpoint(name = "RedemptionServicesSOAP")
    public RedemptionServices getRedemptionServicesSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://b2b.tracfone.com/RedemptionServices/", "RedemptionServicesSOAP"), RedemptionServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REDEMPTIONSERVICES_EXCEPTION!= null) {
            throw REDEMPTIONSERVICES_EXCEPTION;
        }
        return REDEMPTIONSERVICES_WSDL_LOCATION;
    }

}
