
package com.tracfone.b2b.redemptionservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RedemptionServices", targetNamespace = "http://b2b.tracfone.com/RedemptionServices/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.tracfone.runtimefault.ObjectFactory.class,
    com.tracfone.accountcommontypes.ObjectFactory.class,
    com.tracfone.b2b.redemptionservices.ObjectFactory.class,
    com.tracfone.carriercommontypes.ObjectFactory.class,
    com.tracfone.commontypes.ObjectFactory.class,
    com.tracfone.paymentcommontypes.ObjectFactory.class,
    com.tracfone.phonecommontypes.ObjectFactory.class,
    com.tracfone.securitycommontypes.ObjectFactory.class,
    com.tracfone.serviceplancommontypes.ObjectFactory.class
})
public interface RedemptionServices {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.redemptionservices.PINCardRedemptionResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/RedemptionServices/redeemPinCard")
    @WebResult(name = "redeemPINCardResponse", targetNamespace = "http://b2b.tracfone.com/RedemptionServices", partName = "parameters")
    public PINCardRedemptionResponseType redeemPinCard(
        @WebParam(name = "redeemPINCardRequest", targetNamespace = "http://b2b.tracfone.com/RedemptionServices", partName = "parameters")
        PINCardRedemptionRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.redemptionservices.PINCardQueuingResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/RedemptionServices/queuePinCard")
    @WebResult(name = "queuePINCardResponse", targetNamespace = "http://b2b.tracfone.com/RedemptionServices", partName = "parameters")
    public PINCardQueuingResponseType queuePinCard(
        @WebParam(name = "queuePINCardRequest", targetNamespace = "http://b2b.tracfone.com/RedemptionServices", partName = "parameters")
        PINCardQueuingRequestType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.redemptionservices.QueuedPINCardRedemptionResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/RedemptionServices/redeemQueuedPinCard")
    @WebResult(name = "redeemQueuedPINCardResponse", targetNamespace = "http://b2b.tracfone.com/RedemptionServices", partName = "parameters")
    public QueuedPINCardRedemptionResponseType redeemQueuedPinCard(
        @WebParam(name = "redeemQueuedPINCardRequest", targetNamespace = "http://b2b.tracfone.com/RedemptionServices", partName = "parameters")
        QueuedPINCardRedemptionRequestType parameters);

}
