
package com.tracfone.b2b.phoneservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PhoneServices", targetNamespace = "http://b2b.tracfone.com/PhoneServices/", wsdlLocation = "http://dp-sit1-soa3:9001/B2B/PhoneServices?wsdl")
public class PhoneServices_Service
    extends Service
{

    private final static URL PHONESERVICES_WSDL_LOCATION;
    private final static WebServiceException PHONESERVICES_EXCEPTION;
    private final static QName PHONESERVICES_QNAME = new QName("http://b2b.tracfone.com/PhoneServices/", "PhoneServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dp-sit1-soa3:9001/B2B/PhoneServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONESERVICES_WSDL_LOCATION = url;
        PHONESERVICES_EXCEPTION = e;
    }

    public PhoneServices_Service() {
        super(__getWsdlLocation(), PHONESERVICES_QNAME);
    }

    public PhoneServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PHONESERVICES_QNAME, features);
    }

    public PhoneServices_Service(URL wsdlLocation) {
        super(wsdlLocation, PHONESERVICES_QNAME);
    }

    public PhoneServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PHONESERVICES_QNAME, features);
    }

    public PhoneServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PhoneServices
     */
    @WebEndpoint(name = "PhoneServicesSOAP")
    public PhoneServices getPhoneServicesSOAP() {
        return super.getPort(new QName("http://b2b.tracfone.com/PhoneServices/", "PhoneServicesSOAP"), PhoneServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneServices
     */
    @WebEndpoint(name = "PhoneServicesSOAP")
    public PhoneServices getPhoneServicesSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://b2b.tracfone.com/PhoneServices/", "PhoneServicesSOAP"), PhoneServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PHONESERVICES_EXCEPTION!= null) {
            throw PHONESERVICES_EXCEPTION;
        }
        return PHONESERVICES_WSDL_LOCATION;
    }

}
