
package com.tracfone.b2b.inventoryservices;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventoryServices", targetNamespace = "http://b2b.tracfone.com/InventoryServices/", wsdlLocation = "http://dp-sit1-soa3:9001/B2B/InventoryServices?wsdl")
public class InventoryServices_Service
    extends Service
{

    private final static URL INVENTORYSERVICES_WSDL_LOCATION;
    private final static WebServiceException INVENTORYSERVICES_EXCEPTION;
    private final static QName INVENTORYSERVICES_QNAME = new QName("http://b2b.tracfone.com/InventoryServices/", "InventoryServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dp-sit1-soa3:9001/B2B/InventoryServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTORYSERVICES_WSDL_LOCATION = url;
        INVENTORYSERVICES_EXCEPTION = e;
    }

    public InventoryServices_Service() {
        super(__getWsdlLocation(), INVENTORYSERVICES_QNAME);
    }

    public InventoryServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORYSERVICES_QNAME, features);
    }

    public InventoryServices_Service(URL wsdlLocation) {
        super(wsdlLocation, INVENTORYSERVICES_QNAME);
    }

    public InventoryServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORYSERVICES_QNAME, features);
    }

    public InventoryServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventoryServices
     */
    @WebEndpoint(name = "InventoryServicesSOAP")
    public InventoryServices getInventoryServicesSOAP() {
        return super.getPort(new QName("http://b2b.tracfone.com/InventoryServices/", "InventoryServicesSOAP"), InventoryServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryServices
     */
    @WebEndpoint(name = "InventoryServicesSOAP")
    public InventoryServices getInventoryServicesSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://b2b.tracfone.com/InventoryServices/", "InventoryServicesSOAP"), InventoryServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORYSERVICES_EXCEPTION!= null) {
            throw INVENTORYSERVICES_EXCEPTION;
        }
        return INVENTORYSERVICES_WSDL_LOCATION;
    }

}
