
package com.tracfone.b2b.inventoryservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventoryServices", targetNamespace = "http://b2b.tracfone.com/InventoryServices/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.tracfone.runtimefault.ObjectFactory.class,
    com.tracfone.b2b.inventoryservices.ObjectFactory.class,
    com.tracfone.commontypes.ObjectFactory.class
})
public interface InventoryServices {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.tracfone.b2b.inventoryservices.CreateResourceResponseType
     */
    @WebMethod(action = "http://b2b.tracfone.com/InventoryServices/createResource")
    @WebResult(name = "createResourceResponse", targetNamespace = "http://b2b.tracfone.com/InventoryServices", partName = "parameters")
    public CreateResourceResponseType createResource(
        @WebParam(name = "createResourceRequest", targetNamespace = "http://b2b.tracfone.com/InventoryServices", partName = "parameters")
        CreateResourceRequestType parameters);

}
